"""Embedder port."""
from __future__ import annotations
from typing import Protocol, Sequence, runtime_checkable

@runtime_checkable
class Embedder(Protocol):
    @property
    def model_name(self) -> str: ...
    @property
    def dimensions(self) -> int: ...
    def embed_texts(self, texts: Sequence[str]) -> list[list[float]]: ...
    def embed_one(self, text: str) -> list[float]: ...
